### ISSUE TITLE
在？为什么没有utf8文件头？

### ISSUE THREAD

**Issue by simon300000** [dd-center/bilibili-vtuber-live-danmaku-relay#2]
https://stackoverflow.com/questions/17879198/adding-utf-8-bom-to-string-blob/27975629#answer-27975629
感谢@wudifeixue

**Comment by wudifeixue** [comment]
可以的，这个主要解决txt和csv乱码问题，不知道这个配合https://github.com/bilibili-dd-center/txt_to_csv
能否txt改好了csv也直接不出乱码了。

**Comment by simon300000** [comment]
我准备在http请求的文件头加，保存的文件不加
你觉得怎么样？

**Comment by simon300000** [comment]
csv的话，我也去提一个issue吧

**Comment by wudifeixue** [comment]
只要能解决乱码问题的话，怎么样都很好啊。

**Comment by simon300000** [comment]
header这样似乎是ok了
